version: "3.3"

services:
  spark-master:
    image: esumitra/cluster-apache-spark:3.2.1
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
       - ./spark/apps:/opt/spark-apps
       - ./spark/checkpoints:/opt/spark-checkpoints
      #  - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master

  spark-worker-a:
    image: esumitra/cluster-apache-spark:3.2.1
    container_name: spark-worker-a
    ports:
      - "8081:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./spark/apps:/opt/spark-apps
       - ./spark/checkpoints:/opt/spark-checkpoints
      #  - ./data:/opt/spark-data
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  postgres:
    image: postgres:11.7-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - TZ=GMT+10
      - PGTZ=GMT+10
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=casa1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d
